###############################################################################
# zConomy Configuration File
###############################################################################

# Name of the database in DbShare
DatabaseName: Main

# Name of the economy table
TableName: zConomy

# Currency names
CurrencyName:
  Singular: 'Dollar'
  Plural: 'Dollars'

# Default balance of a new account
DefaultBalance: 500.0

# Formats
Formats:

  NoAccountForConsole: 'Console does not have and cannot have a bank account.'
  NoAccountFound: '&8[&c!&8] &cMoney &8[&c!&8] &a{0} &7does not have an account.'
  ExistingAccountFound: '&8[&c!&8] &cMoney &8[&c!&8] &a{0} &7already has an account.'
  InvalidAmount: '&8[&c!&8] &cMoney &8[&c!&8] &f{0} &7is not a valid amount.'
  NoPermission: '&8[&c!&8] &cMoney &8[&c!&8] &7You do not have the &f{0} &7permission.'

  AccountCreated: '&8[&9!&8] &9Money &8[&9!&8] &7Created account for &a{0}'
  AccountRemoved: '&8[&9!&8] &9Money &8[&9!&8] &7Removed account for &a{0}'
  AccountBalance: '&8[&9!&8] &9Money &8[&9!&8] &7Balance: &f{0}'
  AccountSet: '&8[&9!&8] &9Money &8[&9!&8] &7Set balance for &a{0} &7to &f{1}'
  AccountGive: '&8[&9!&8] &9Money &8[&9!&8] &7Given &f{0} &7to &a{1}'
  AccountTake: '&8[&9!&8] &9Money &8[&9!&8] &7Took &f{0} &7from &a{1}'

  PaySent: '&8[&9!&8] &9Money &8[&9!&8] &7You sent &f{0} &7to &a{1}'
  PayReceived: '&8[&9!&8] &9Money &8[&9!&8] &7You received &f{0} &7from &a{1}'
  InsufficientFunds: '&8[&c!&8] &cMoney &8[&c!&8] &7You do not have &f{0}.'
  PayToSelf: '&8[&c!&8] &cMoney &8[&c!&8] &7You cannot pay yourself.'

  TopListHeader: '&8[&9!&8] &9Money &8[&9!&8] &7Displaying Top 10 accounts:'
  TopListItemFormat: '&7{0}. &f{1} &7has &f{2}'

  GeneralFailure: '&8[&c!&8] &cMoney &8[&c!&8] &fUh oh! Report this to an admin or dev: {0}'
  ConfigReloaded: '&8[&9!&8] &9Money &8[&9!&8] &7Configuration reloaded'

  CreateUsage: '/money create <name>'
  GiveUsage: '/money give <name> <amount>'
  PayUsage: '/money pay <name> <amount>'
  SetUsage: '/money set <name> <amount>'
  TakeUsage: '/money take <name> <amount>'

  HelpMessage: |
               /money - &7Check your balance&r
               /money create <name> - &7Create a new bank account&r
               /money give <name> <amount> - &7Add money to a bank account&r
               /money help - &7Display this help message&r
               /money pay <name> <amount> - &7Transfer money from your bank account to another&r
               /money purge - &7Remove banks with the default money&r
               /money remove <name> - &7Remove a bank account&r
               /money set <name> <amount> - &7Set the money for a bank account&r
               /money take <name> <amount> - &7Take money from a bank account&r
               /money top - &7Find the top 10 bank accounts with the most money&r

# Debug Mode?
DebugMode: False
