name: zConomy
main: com.gmail.tracebachi.zConomy.zConomyPlugin
version: ${project.version}
author: GeeItsZee (tracebachi@gmail.com)
depend: [Vault, DbShare]
commands:
  money:
    description: Main command for the plugin
    aliases: [balance, bal]
permissions:
  zConomy.Create:
    description: Create accounts.
  zConomy.Give:
    description: Give money to accounts.
  zConomy.Pay:
    description: Make payments to others.
  zConomy.Remove:
    description: Remove accounts.
  zConomy.Set:
    description: Set money for an account.
  zConomy.Take:
    description: Take money from accounts.
  zConomy.Top:
    description: View top accounts.
